app/relationship/__init__.py
from flask import Blueprint

bp = Blueprint('relationship', __name__)

from app.relationship import routes

app/relationship/routes.py
import re
from urllib import parse

from flask import (flash, redirect, render_template, request, url_for, jsonify,
                   current_app)
from flask_login import current_user, login_required


from app.extensions import db
from app.relationship.forms import (GroupSearchForm, FriendDeleteForm,
                                    FriendSearchForm, GroupCreateForm,
                                    GroupEditForm, FriendApproveForm,
                                    GroupDeleteForm, GroupMemberApproveForm,
                                    GroupAddForm)
from app.models import User, Group, FriendRequest, GroupRequest, Review
from app.utilities.helpers import disableForm, email_verified, listToString
from app.utilities.pagination import Pagination
from app.relationship import bp


def groups_render(form=None, code=200):
    """Populate necessary fields for groups network page and render template."""
    modal = False

    if form.__class__ == GroupSearchForm:
        GroupSearch = form
    else:
        GroupSearch = GroupSearchForm()
    if form.__class__ == GroupDeleteForm:
        GroupDelete = form
        modal = "#GroupDelete"
    else:
        GroupDelete = GroupDeleteForm().populate_choices(current_user)
    if form.__class__ == GroupMemberApproveForm:
        GroupMemberApprove = form
        modal = "#pending_groups"
    else:
        GroupMemberApprove = GroupMemberApproveForm().populate_choices(current_user)

    modal_open = {"modal": modal}

    return render_template(
        "relationship/network_groups.html", GroupSearch=GroupSearch,
        title="Groups", GroupDelete=GroupDelete, modal_open=modal_open,
        GroupMemberApprove=GroupMemberApprove,
        GroupRequest=GroupRequest
    ), code


def friends_render(form=None, code=200):
    """Populate necessary fields for friends network page and render template."""
    modal = False

    if form.__class__ == FriendSearchForm:
        FriendSearch = form
    else:
        FriendSearch = FriendSearchForm()
    if form.__class__ == FriendDeleteForm:
        FriendDelete = form
        modal = "#FriendDelete"
    else:
        FriendDelete = FriendDeleteForm().populate_choices(current_user)
        FriendDelete.populate_choices(current_user)
    if form.__class__ == FriendApproveForm:
        FriendApprove = form
        modal = "#pending_friends"
    else:
        FriendApprove = FriendApproveForm().populate_choices(current_user)

    modal_open = {"modal": modal}

    return render_template(
        "relationship/network_friends.html", FriendSearch=FriendSearch,
        title="Friends", FriendDelete=FriendDelete,
        FriendApprove=FriendApprove, modal_open=modal_open
    ), code


@bp.route('/network/friends/add', methods=['POST'])
@login_required
def friendadd():
    """Send friend request to add friend."""
    form = FriendSearchForm()
    if form.validate_on_submit():
        request_args = {"requestor_id": current_user.id,
                        "friend_id": form.id.data}
        request = FriendRequest.query.filter_by(**request_args).first()
        if not request:
            request = FriendRequest.create(**request_args)
        request.send()
        flash(
            f"Friend request sent to {request.requested_friend.full_name}."
            "  Awaiting confirmation."
        )
        return redirect(url_for('relationship.network_friends'))
    else:
        flash(
            f"Friend request unsucessful.  {' '.join(form.id.errors)}"
            f"  Please correct errors and resubmit."
        )
        return friends_render(form, 422)


@bp.route('/network/friends/approve', methods=['POST'])
@login_required
def friend_approve():
    """Approve friend requests from network page."""
    form = FriendApproveForm()
    form.populate_choices(current_user)
    if form.validate_on_submit():
        newFriends = []
        for friendrequest_id in form.name.data:
            friendrequest = FriendRequest.query.get(friendrequest_id)
            new_friend = friendrequest.requestor
            current_user.add(new_friend, friendrequest)
            newFriends.append(new_friend.full_name)
        flash(f"You are now friends with {listToString(newFriends)}.")
        return redirect(url_for('relationship.network_friends'))
    else:
        flash(
            f"Request to add friend failed.  Please correct errors and"
            " resubmit."
        )
        return friends_render(form, 422)


@bp.route('/network/friends/remove', methods=['POST'])
@login_required
def friend_remove():
    """Remove friend from user's list of friends."""
    form = FriendDeleteForm()
    form.populate_choices(current_user)
    if form.validate_on_submit():
        removed = []
        for person in form.name.data:
            toBeRemoved = User.query.get(person)
            try:
                current_user.remove(toBeRemoved)
                removed.append(toBeRemoved.full_name)
            except ValueError:
                flash(
                    "Invalid request. You can't remove someone that you aren't"
                    " friends with."
                )
        current_user.save()
        if len(removed) == 1:
            flash(f"{removed[0]} has been removed from your friends")
        else:     
            flash(f"{', '.join(removed)} have been removed from your friends")
        return redirect(url_for('relationship.network_friends'))
    flash("Invalid request. Please correct errors and resubmit.")
    return friends_render(form, 422)


@bp.route('/network/friends/search', methods=['GET'])
@login_required
def friendsearch():
    """Searches db for groups to populate group search autocomplete"""
    name = parse.unquote_plus(request.args.get("name"))
    a = re.compile('[^a-zA-Z]+')
    name = f'%{a.sub("", name)}%'
    users = (User.query.filter(
        (User.first_name + User.last_name).ilike(name)
        | (User.last_name + User.first_name).ilike(name)
        )
        .order_by(User.last_name, User.first_name)
        .limit(10))
    users = users.all()
    names = ([
        {
            "id": person.id,
            "first_name": person.first_name,
            "last_name": person.last_name,
            "city": person.address.city,
            "state": person.address.state.state_short
        }
        for person in users
    ])
    return jsonify(names)


@bp.route('/friendverify/<token>')
def friend_verify(token):
    """Verify friend request add token and add person to friend list."""
    friendrequest = FriendRequest.verify_token(token)
    if not friendrequest:
        msg = "Friend request verification failed. Please either log in to "\
              "submit new request or have requestor re-submit."
    else:
        approver = friendrequest.requested_friend
        friend = friendrequest.requestor
        approver.add(friend, friendrequest)
        msg = f"You are now friends with {friend.full_name}."
        if not approver.email_verified:
            approver.update(email_verified=True)
    flash(msg)
    return redirect(url_for('auth.welcome'))


@bp.route('/group/<name>/<id>')
@login_required
@email_verified
def group(name, id):
    group = Group.query.filter_by(id=id).first()
    if not group:
        flash("Invalid group requested.")
        if request.referrer:
            return redirect(request.referrer)
        else:
            return redirect(url_for('relationship.network_groups'))
    else:
        if current_user == group.admin:
            modal_form = GroupEditForm(
                name=group.name, description=group.description, id=group.id
            )
            modal_title = "Edit Group"
        else:
            modal_form = False
            modal_title = None
        reviews = Review.search(group_id=group.id)
        page = request.args.get('page', 1, int)
        pagination = Pagination(
            reviews, page, current_app.config.get('PER_PAGE')
        )
        pag_args = {"name": name, "id": id}
        pag_urls = pagination.get_urls('relationship.group', pag_args)
        reviews = pagination.paginatedData
        return render_template(
            "relationship/group.html", group=group, modal_form=modal_form,
            modal_title=modal_title, reviews=reviews, pag_urls=pag_urls,
            title="Group Profile"
        )


@bp.route('/network/groups/add', methods=['POST'])
@login_required
def groupadd():
    """Send group admin request to join group."""
    form = GroupAddForm()
    if form.validate_on_submit():
        group = Group.query.get(form.id.data)
        if current_user != group.admin:
            args = {
                "group_id": group.id, "requestor_id": current_user.id
            }
            request = GroupRequest.query.filter_by(**args).first()
            if not request:
                request = GroupRequest.create(**args)
            request.send()
            msg = (
                f"Request sent to join {group.name}. Awaiting group admin "
                "confirmation."
            )
        else:
            current_user.add(group)
            msg = f"Successfully added to {group.name}."
        flash(msg)
        return groups_render()
    else:
        for error in form.errors['id']:
            flash(error)
        return groups_render(code=422)


@bp.route('/network/groups/approve', methods=['POST'])
@login_required
def group_approve():
    """Approve group requests from network page."""
    form = GroupMemberApproveForm()
    form.populate_choices(current_user)
    if form.validate_on_submit():
        for request_id in form.request.data:
            grouprequest = GroupRequest.query.get(request_id)
            group = grouprequest.group
            user = grouprequest.requestor
            user.add(group, grouprequest)
            flash(f"{user.full_name} is now a member of {group.name}.")
        current_user.save()
        return redirect(url_for('relationship.network_groups'))
    else:
        flash(

app/templates/relationship/network.html
{% extends "double_column.html" %}
{% from "macros.html" import form_render, field_render, modal_render, modal_render_objectlist %}

{% block content_left_top %}
    <form action="/groupadd" method="post">
        {{form_render(GroupSearch)}}
        <a href="{{url_for('relationship.group_create')}}">Create New Group</a>
    </form>
{% endblock %}
    
{% block content_right_top %}
    <form action="/friendadd" method="post">
        {{form_render(FriendSearch)}}
    </form>
{% endblock %}
    
    
{% block content_left_bottom %}
    <div id="network"></div>
    <!-- list of groups user belongs to -->
    <div class="row">
    <h3>Your Groups</h3>
    <ul class="nav">
            {% set pending_count = current_user.sentgrouprequests | count + 
               current_user.get_group_admin_choices() | count %}
            <a href="" class="nav-link" data-toggle="modal" data-target="#pending_groups">Pending<span>({{pending_count}})</span></a>
            <a href="" class="nav-link" data-toggle="modal" data-target="#GroupDelete">Delete</a>
        </li>
    </ul>
    </div>
    <ul>
        {% for group in current_user.groups %}
        <li> 
        <a href="{{url_for('relationship.group', name=group.name, id=group.id)}}">
        {{ group["name"] }} </a></li>
        {% endfor %}
    </ul>
    <br>
{% endblock %}

{% block content_right_bottom %}
    <div class="row">
        <h3> Your Friends</h3>
        <ul class="nav">
                {% set pending_count = current_user.sentfriendrequests|count + current_user.receivedfriendrequests|count %}
                <a href="" class="nav-link" data-toggle="modal" data-target="#pending_friends">Pending<span>({{pending_count}})</span></a>
                <a href="" class="nav-link" data-toggle="modal" data-target="#FriendDelete">Delete</a>
            </li>
        </ul>
    </div>   

    <ul>
        {% for friend in current_user.friends %}
        <li> 
            <a href="{{url_for('main.user', username=friend.username)}}">
                {{friend.full_name}} </a></li>
                {% endfor %}
            </ul>
            <br>
            {% endblock %}
            
{% block modal %}

    {% if modal_open['modal'] != false %}
        
        <script>
            var modal = {{modal_open|tojson}}.modal
            console.log(modal)
            $(window).on('load', function(){
            $(modal).modal('show');
        });
        </script>
    {% endif %}
 
    <!--Modal to delete friends -->
    {{modal_render(FriendDelete, "Delete Friends", action=url_for('relationship.friend_remove'), modalID="FriendDelete")}}

    <!-- Modal to delete groups -->
    {{modal_render(GroupDelete, "Delete Groups", action=url_for('relationship.group_remove'), modalID="GroupDelete")}}

    <!-- Modal for Pending Friend Requests / approval of incoming requests -->
    <div class="modal" id="pending_friends" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-md modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h3 class="modal-title">Pending Friends</h3>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body px-5">
                    <h5>Sent</h5>
                        <ul>
                            {% if current_user.get_requested_friends() == [] %}
                                <li>None</li>
                            {% else %}
                                {% for friend in current_user.get_requested_friends() %}
                                    <li>{{friend|attr('full_name')}}</li>
                                {% endfor %}
                            {% endif %}
                        </ul>
                    <!--display form if users to approve or list with none -->
                    {% if current_user.receivedfriendrequests != [] %}
                        <form id = "modal_form_group" action="{{url_for('relationship.friend_approve')}}" method="POST">
                            <h5>Received <small>(Select and submit to approve)</small></h5>
                            {{FriendApprove.hidden_tag()}}
                            {{FriendApprove.name()}}
                            {% if FriendApprove.name.errors|length > 0 %}
                            <span style="color:red;">{{field.errors}}</span>
                            {% endif %}
                    {% else %}
                        <h5>Received</h5>
                            <ul>
                                <li>None</li>
                            </ul>
                    {% endif %}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    {% if current_user.receivedfriendrequests != [] %}
                        {{FriendApprove.submit(class_=("btn btn-primary btn-block-submit submit"))}}
                        </form>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

    <!-- Modal for Pending Group Requests / admin approval of incoming requests -->
    <div class="modal" id="pending_groups" tabindex="-1" role="dialog">
            <div class="modal-dialog modal-md" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h3 class="modal-title">Pending Groups</h3>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body px-5">
                        <h5>Sent</h5>
                            <ul>
                                {% if current_user.sentgrouprequests == [] %}
                                    <li>None</li>
                                {% else %}
                                    {% for request in current_user.sentgrouprequests %}
                                        <li>{{request.group.name}}</li>
                                    {% endfor %}
                                {% endif %}
                            </ul>
                        <!--if admin display none or list of pending approvals -->
                        {% if current_user.group_admin | length > 0 %}
                            {% if GroupRequest.get_pending(current_user) != [] %}
                            <form id = "modal_form_group" action="{{url_for('relationship.group_approve')}}" method="POST">
                                <h5>Received <small>(Select and submit to approve)</small></h5>
                                {{GroupMemberApprove.hidden_tag()}}
                                {{GroupMemberApprove.request()}}
                                {% if GroupMemberApprove.errors|length > 0 %}
                                <span style="color:red;">{{field.errors}}</span>
                                {% endif %}
                            {% else %}
                                <h5>Received</h5>
                                    <ul>
                                        <li>None</li>
                                    </ul>
                            {% endif %}
                        {% endif %}
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        {% if GroupRequest.get_pending(current_user) != [] %}
                            {{FriendApprove.submit(class_=("btn btn-primary btn-block-submit submit"))}}
                            </form>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>

{% endblock %}